### PR TITLE
Adding status code field to Response class (interfaces)

### PR DESCRIPTION
**Pull request by busslina**
Adding missing status code field to Response class interfaces

### CODE REVIEW

**Comment by paulober** [comment]
Here is the source code of this module:
https://github.com/micropython/micropython-lib/blob/master/python-ecosys/urequests/urequests.py
And here is the output of available fields and methods in the response class (using latest Firmware for Pico W):
image
I don't find the field you want to add...

**Comment by paulober** [comment]
@busslina Maybe they removed it again as this field is not present in the current firmware ([v1.19.1-915-g2bcd88d55 (2023-03-02) .uf2](https://micropython.org/resources/firmware/rp2-pico-w-20230302-unstable-v1.19.1-915-g2bcd88d55.uf2))

**Comment by busslina** [comment]
I'm able to read this value like this:

imagen

**Comment by busslina** [comment]
Also status code is the minimum thing that a HTTP Response has to possess

**Comment by paulober** [comment]
@busslina Thanks for the details. It seems like MPY sets this field on runtime thats why it has not been detected. I'll check the stubs for other issues like this...

**Pull request merged**
